dotenv: .env
dependencies:
#   - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - smartcontractkit/chainlink@1.4.1
compiler:
  solc:
    version: 0.8.7
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.4.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
#       - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2/contracts'
# networks:
#   default: ganache
  # kovan:
  #   verify: True
  # rinkeby:
  #   verify: True
  # hardhat:
  #   verify: False
wallets:
  studentTestAccount: ${studentTestAccount}
  multiversityTestAccount: ${multiversityTestAccount}
  employerTestAccount: ${employerTestAccount}
  instructorTestAccount: ${instructorTestAccount}
